### ISSUE TITLE
vetší text u konkrétních služieb 1.5x

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#18]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/8fb50785-8e49-440e-b1fa-a90b16991e77)

**Comment by marosstudenic** [comment]
vyzera to lepsie s mensim textom @sarka

**Comment by dev-Leone** [comment]
prepáč, chyby na mojej strane. Myslela toto
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/ef30baf6-e829-4a00-842c-6086dc830771)
