### ISSUE TITLE
vačšie

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#27]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/4c739957-2794-4268-94d6-fe7c97e32181)
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/bb552e8b-bfb5-4bf9-8b7b-a71ea30fa4e4)

**Comment by marosstudenic** [comment]
potrebujem design na hranici bez backgriundu alebo aby mal rovnaky background - farbu sedej ako je na webe, lebo zvysne obrazky maju presne taku sedu

**Comment by marosstudenic** [comment]
fixnut
