### ISSUE TITLE
prec scharfyn a vymenit podla figmy

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#30]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/fbe7fa4f-b2fb-4320-96fa-abd444ea5a6b)

**Comment by marosstudenic** [comment]
co vymenit podla figmy, ved vo figme je stale schafryn

**Comment by dev-Leone** [comment]
opravene, prepáč
