### ISSUE TITLE
podla figmy cely formular

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#36]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/a7f0343e-9a2b-4c51-9e0e-3a0b830cb02a)

**Comment by dev-Leone** [comment]
aj dalsie casti

**Comment by dev-Leone** [comment]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/db2d9868-6143-4fcf-af6b-b2036d1d84fe)
napravo tlacitka

**Comment by dev-Leone** [comment]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/a23290c9-9100-4e06-bc48-6e97d0c9a466)
zarovnat vaša vizia s menom a nech sa po doplneni dostatočneho textu píše na daľši riadok
daj tam namiesto spojovniku  pomlcku pri cene a  oddeluj po 3 cifrach

**Comment by dev-Leone** [comment]
chýba na vloženie dokumentu

**Comment by marosstudenic** [comment]
kedze ten provider, ktory pouzivam na odosielanie emailov nepodporuje zatial posielanie suborov  a neni nakodeny backend na spracovanie suborov a formularov, tak toto zatial odkladam.

Zvysok by mal byt fixnuty +-
