### ISSUE TITLE
vymen prosim ta 

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#54]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/281f6809-94b3-498f-a932-3dddcd2096a1)

**Comment by dev-Leone** [comment]
za Kreatívna Vizuálna Identita a Úspešný Branding

**Comment by marosstudenic** [comment]
vymenene, ale nejde to tak dobre zalomit aby to davalo zmysel
