### ISSUE TITLE
tento  

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#61]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/19b30593-d3e8-41fc-8590-0577695928fa)

**Comment by marosstudenic** [comment]
co tento ?

**Comment by dev-Leone** [comment]
Že tento design, to bolo skôr informačne. Vtedy sme sa bavili a nevedeli sme sa dohodnut aky design je aktualny
