### ISSUE TITLE
keby sa dalo takto nejak na telefon, prosím ťa (logo na pravo bude menu)

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#63]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/7171c98d-de03-492c-9ed3-d57a7ec797c1)

**Comment by marosstudenic** [comment]
kde menucko ?

**Comment by marosstudenic** [comment]
inak je to upavene
