### ISSUE TITLE
why gone?

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#66]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/cd3cfee1-c02b-482a-a0b2-2c13063d6433)
chýba podtrhnutie

**Comment by dev-Leone** [comment]
nav bar btw

**Comment by marosstudenic** [comment]
lebo tento issue 
https://github.com/marosstudenic/schulz-concept-agency/issues/13

cize som to pochopil tak, ze to chces odstranit

**Comment by SCHARFYNN** [comment]
Prostrkání jsou mezery mezi znakama právě

**Comment by marosstudenic** [comment]
neviem, ci nechapem kvoli cestine, alebo ako. dal som naspat underline

**Comment by marosstudenic** [comment]
sirka medzi znakmi
