### ISSUE TITLE
link na kontakt

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#67]
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/e6f938d1-b5b3-4204-96db-6dfc3543f2b2)

**Comment by marosstudenic** [comment]
aky link na kontakt ? joj, treba byt specifickejsi pri tom pisani issues.

**Comment by dev-Leone** [comment]
Keby sa to prosim ta dalo dat na celu tuto cast (čo sa hýbe) ako link na https://schulzconcept.eu/contact/
