### ISSUE TITLE
animácia pri kontaktuj nas sa sekane resetne, spraviť perfect loop?

### ISSUE THREAD

**Issue by dev-Leone** [marosstudenic/schulz-concept-agency#7]

**Comment by dev-Leone** [comment]
Dá sa to nejak nekonecne nakopirovať? 
![image](https://github.com/marosstudenic/schulz-concept-agency/assets/144813795/9681e9af-d053-450e-8233-7eb500a62d3a)

**Comment by marosstudenic** [comment]
malo by to byt teraz lepsie.  treba check

**Comment by dev-Leone** [comment]
stale to robi ale ako po cca 10-15s

**Comment by dev-Leone** [comment]
ale je to pekne do krajov, ďakujem
